version: '2.1'
volumes:
  core-storage:
  reports-storage:
  leviathan:
services:
  core:
    privileged: true
    build:
      context: ./core
      ports:
        - "80:80"
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
      - 'leviathan:/run/leviathan'
    labels:
      share: core-storage
      io.balena.features.balena-socket: '1'
      io.balena.features.dbus: '1'
  worker:
    privileged: true
    build:
      context: ./worker
    pid: host
    network_mode: host
    ipc: host
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
      - 'leviathan:/run/leviathan'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.balena-socket: '1'
      io.balena.features.balena-api: '1'
