version: '2.1'
volumes:
  core-storage:
  reports-storage:
services:
  worker:
    privileged: true
    build: .
    pid: host
    network_mode: host
    ipc: host
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
    environment:
      - UDEV=1
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.balena-socket: '1'
      io.balena.features.balena-api: '1'
      io.balena.features.kernel-modules: '1'
