version: '2'
services:
  client:
    build: ./client
    network_mode: host
    volumes:
      - "${WORKSPACE:-./workspace}:/usr/src/app/workspace:ro"
      - "${REPORTS:-./workspace/reports}:/usr/src/app/reports:rw"
      - "${SUITES:-./suites}:/usr/src/app/suites:ro"
    environment:
      - BALENACLOUD_API_KEY=${BALENACLOUD_API_KEY}
      - BALENACLOUD_ORG=${BALENACLOUD_ORG}
  core:
    build: ./core
    network_mode: 'host'
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
    environment:
      - UDEV=0
      - CORE_PORT=${CORE_PORT}
