version: '2.1'
services:
  core:
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
  worker:
    build:
      context: ./worker
      args:
        - SKIP_INSTALL_BINARY=true
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN # allow network setup
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - SCREEN_CAPTURE=true
    pid: ''
    ipc: ''
