version: "2"

services:
  core:
    privileged: true
    build:
      context: ./core
    volumes:
      - "${WORKSPACE:-./workspace}:/usr/src/app/workspace:rw"
      - "${DATA:-./workspace/data}:/data:rw"
      - "${REPORTS:-./workspace/reports}:/reports:rw"
    tmpfs:
      - /var/run # use tmpfs docker-in-docker pid files
      - /var/lib/docker # use tmpfs for docker-in-docker data root
    restart: 'no'

volumes:
  core-storage:
  reports-storage:
