version: "2.4"
volumes:
  core-storage:
  reports-storage:
services:
  core:
    build: ./core
    network_mode: 'host'
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - WORKER_PORT=${WORKER_PORT}
      - CORE_PORT=${CORE_PORT}
  worker:
    build: 
      context: ./worker
      args:
        - SKIP_INSTALL_BINARY=true
    device_cgroup_rules:
        # allow dynamic creation and access of qemu required misc chardev nodes
        # this includes /dev/kvm, and /dev/net/tun
      - 'c 10:* rmw'
    cap_add:
      - NET_ADMIN # allow network setup
    network_mode: 'host'
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - SCREEN_CAPTURE=true
      - WORKER_PORT=${WORKER_PORT}
