version: '2.1'
volumes:
  core-storage_2:
  reports-storage_2:
  core-storage_3:
  reports-storage_3:
services:
  core:
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - CORE_PORT=81
      - WORKER_PORT=2001
  worker:
    build:
      context: ./worker
      args:
        - SKIP_INSTALL_BINARY=true
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN # allow network setup
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - SCREEN_CAPTURE=true
      - WORKER_PORT=2001
    pid: ''
    ipc: ''
  core_2:
    extends:
      service: core
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - CORE_PORT=82
      - WORKER_PORT=2002
    volumes:
      - 'core-storage_2:/data'
      - 'reports-storage_2:/reports'
  worker_2:
    extends:
      service: worker
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - SCREEN_CAPTURE=true
      - WORKER_PORT=2002
    volumes:
      - 'core-storage_2:/data'
      - 'reports-storage_2:/reports'
  core_3:
    extends:
      service: core
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - CORE_PORT=83
      - WORKER_PORT=2003
    volumes:
      - 'core-storage_3:/data'
      - 'reports-storage_3:/reports'
  worker_3:
    extends:
      service: worker
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - SCREEN_CAPTURE=true
      - WORKER_PORT=2003
    volumes:
      - 'core-storage_3:/data'
      - 'reports-storage_3:/reports'
  