- name: author
  type: Short Text
- name: timestamp
  type: Date
- name: device_type
  type: Short Text
- name: image_size
  type: Text
- name: provision_time
  type: Text
- name: balena_os_version
  type: Semver
- name: body
  type: Text
