version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    parallelism: 1
    machine:
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Clone submodules
          command: git submodule update --init --recursive

      - run:
          name: Build docker image
          command: make build-docker-image

      - run:
          name: Verifying coding style
          command: make code-check

      - run:
          name: Running resinos tests
          command: make
          no_output_timeout: 20m
