version: '2'
volumes:
  core-storage:
  worker-storage:
  reports-storage:
services:
  core:
    privileged: true
    build: ./core
    network_mode: 'host'
    volumes:
      - 'core-storage:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'reports-storage:/reports'
    labels:
      share: 'core-storage'
  worker:
    privileged: true
    build: ./worker
    pid: 'host'
    network_mode: 'host'
    ipc: 'host'
    volumes:
      - '/var/run/dbus:/host/run/dbus:rw'
      - 'reports-storage:/reports'
      - 'worker-storage:/data'
