version: '2'
volumes:
  core-storage:
  reports-storage:
services:
  core:
    build: ./core
    network_mode: 'host'
    privileged: true
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
  worker:
    build: 
      context: ./worker
      args:
        - SKIP_INSTALL_BINARY=true
    devices:
      - "/dev/net/tun:/dev/net/tun"
      - "/dev/kvm:/dev/kvm"
    cap_add:
      - NET_ADMIN # allow network setup
    build: ./worker
    network_mode: 'host'
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - SCREEN_CAPTURE=true
