on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  balena-cloud-build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        fleets: [balena/testbot-rig, balena/testbot-rig-beta, balena/testbot-personal]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: balena-io/deploy-to-balena-action@v0.5.4
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fleet: ${{ matrix.fleets }}
          versionbot: false
          environment: balena-cloud.com
          create_tag: true
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
