name: Check Markdown links

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  schedule:
    - cron: "0 0 * * 1"

jobs:
  markdown-link-check:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.1.1
        with:
          args: >
            --config ./lychee.toml
            --github-token ${{ secrets.GITHUB_TOKEN }}
            **/*.md
